<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RaspberryBeret.Objects\RaspberryBeret.Objects.csproj" />
    <ProjectReference Include="..\RaspberryBeret\RaspberryBeret.csproj" />
  </ItemGroup>

</Project>
